Algoritmo "crescente"

Var

   x,y: inteiro

Inicio

      escreval("Digite dois numeros:")
      leia(x)
      leia(y)
      
      enquanto x <> y faca
      
       se x > y entao
          escreval("Decrescente")
          escreval("Digite outros dois numeros: ")
          leia(x)
          leia(y)
       senao
            escreval("Crescente")
       fimse
       
        escreval("Digite outros dois numeros: ")
        leia(x)
        leia(y)
      fimenquanto

Fimalgoritmo