Algoritmo "media_ponderada"

Var

   i, n: inteiro
   media, x, a, b, c: real

Inicio

      escreva("Quantos casos voce vai digitar? ")
      leia(n)
      
      para i de 1 ate n faca)
           escreval("Digite tres numeros: ")
           leia(a)
           leia(b)
           leia(c)
           media <- (a*2 + b*3 + c*5) / 10
           escreval("Media = ", media:1:1)
      fimpara

Fimalgoritmo